In [1]:
import numpy as np

In [13]:
matrix = np.array([
    [2, 4, 3],
    [1, 0, 0]
])

In [14]:
n = len(matrix)
m = len(matrix[0])

In [15]:
n

2

In [16]:
m

3

In [9]:
matrix

array([[2, 4, 3],
       [1, 0, 0]])

In [12]:
def markRow(matrix, i, j):
    for j in range(m):
        if matrix[i][j] != 0:
            matrix[i][j] = -1
def markCol(matrix, i, j):
    for i in range(n):
        if matrix[i][j] != 0:
            matrix[i][j] = -1

In [24]:
def matrixx(matrix, i, j):
    for i in range(n):
        for j in range(m):
            if matrix[i][j] == 0:
                markRow(matrix, i, j)
                markCol(matrix, i, j)
                
    for i in range(n):
        for j in range(m):
            if matrix[i][j] == -1:
                matrix[i][j] = 0
                
    return matrix

In [25]:
matrix

array([[ 2, -1, -1],
       [-1,  0,  0]])

In [23]:
matrixx(matrix, i, j)

array([[ 2, -1, -1],
       [-1,  0,  0]])

In [53]:
matrix = np.array([[2, 4, 3], [1, 0, 0]])

In [54]:
n = len(matrix)
m = len(matrix[0])

In [55]:
matrix

array([[2, 4, 3],
       [1, 0, 0]])

In [56]:
n

2

In [57]:
m

3

In [60]:
def markRow(matrix, i, j):
    for j in range(m):
        if matrix[i][j] != 0:
            matrix[i][j] = -1
        
def markCol(matrix, i, j):
    for i in range(n):
        if matrix[i][j] != 0:
            matrix[i][j] = -1



def zeromatrix(matrix, n, m):
    for i in range(n):
        for j in range(m):
            if matrix[i][j] == 0:
                markRow(matrix, i, j)
                markCol(matrix, i ,j)
   
    for i in range(n):
        for j in range(m):
            if matrix[i][j] == -1:
                matrix[i][j] = 0
    return matrix

In [61]:
zeromatrix(matrix, n, m)

array([[2, 0, 0],
       [0, 0, 0]])

In [63]:
matrix[:,0]

array([2, 0])

In [2]:
import numpy as np

In [3]:
matrix = np.array([[2, 4, 3], [1, 0, 0]])

In [4]:
matrix

array([[2, 4, 3],
       [1, 0, 0]])

In [5]:
n = len(matrix)
m = len(matrix[0])

In [6]:
row = [0] * n
col = [0] * m

In [7]:
matrix

array([[2, 4, 3],
       [1, 0, 0]])

In [12]:
for i in range(n):
    for j in range(m):
        if matrix[i][j] == 0:
            row[i] = 1
            col[j] = 1
            
for i in range(n):
    for j in range(m):
        if row[i] == 1 or col[j] == 1:
            matrix[i][j] = 0

In [9]:
col

[0, 1, 1]

In [10]:
row

[0, 1]

In [13]:
# Longest Successive Elements
a = [5, 8, 3, 2, 1, 4]
n = len(a)

In [14]:
b = list(set(a))

In [15]:
b

[1, 2, 3, 4, 5, 8]

In [18]:
maxc = float('-inf')
for ele in b:
    if ele - 1 not in b:
        x = ele
        count = 1
        while x + 1 in b:
            x = x + 1
            count += 1
        maxc = max(maxc, count)

In [21]:
b = set()
for i in range(n):
    b.add(a[i])

In [22]:
b

{1, 2, 3, 4, 5, 8}

In [1]:
import numpy as np

In [2]:
matrix = np.array([[2, 4, 3], [1, 0, 0]])

In [3]:
matrix

array([[2, 4, 3],
       [1, 0, 0]])

In [6]:
n = len(matrix)
m = len(matrix[0])

In [5]:
n

2

In [7]:
row = [0] * n
col = [0] * m

In [8]:
for i in range(n):
    for j in range(m):
        if matrix[i][j] == 0:
            row[i] = 1
            col[j] = 1

In [10]:
row

[0, 1]

In [11]:
col

[0, 1, 1]

In [14]:
for i in range(n):
    for j in range(m):
        if row[i] == 1 or col[j] == 1:
            matrix[i][j] = 0

In [15]:
matrix

array([[2, 0, 0],
       [0, 0, 0]])

In [16]:
a = [5, 8, 3, 2, 1, 4]
n = len(a)

In [17]:
b = list(set(a))

In [18]:
b

[1, 2, 3, 4, 5, 8]

In [24]:
longest = 1
for ele in b:
    if ele - 1 not in b:
        x = ele
        cnt = 1
        while x + 1 in b:
            x = x + 1 
            cnt += 1
        longest = max(longest, cnt)

In [25]:
longest

5

In [28]:
a = [1, 2, 3, 2]
n = len(a)

In [38]:
b = []
maxi = float('-inf')
for i in range(n-1, -1, -1):
    if a[i] > maxi:
        b.append(a[i])
    maxi = max(maxi, a[i])
b.sort()

In [39]:
b

[2, 3]

In [76]:
# Find The breaking point
a = [2, 1, 5, 4, 3, 0, 0]
n = len(a)

In [77]:
for i in range(n-2, -1, -1):
    if a[i] < a[i + 1]:
        ind = i
        break
for i in range(n-1, ind, -1):
    if ind < a[i]:
        a[ind], a[i] = a[i], a[ind]
        break
a[ind + 1: ] = reversed(a[ind + 1: ])

In [78]:
a

[2, 3, 0, 0, 1, 4, 5]

In [79]:
brp

1

In [80]:
x

1

In [81]:
a

[2, 3, 0, 0, 1, 4, 5]

In [82]:
a[x + 1:] = reversed(a[x + 1:])

In [83]:
a

[2, 3, 5, 4, 1, 0, 0]

In [84]:
a = a[::-1]

In [85]:
a

[0, 0, 1, 4, 5, 3, 2]

In [1]:
import numpy as np

In [14]:
matrix = np.array([[2, 4, 3], [1, 0, 0]])

In [15]:
n = len(matrix)
m = len(matrix[0])

In [16]:
row = [0] * n
col = [0] * m

In [17]:
for i in range(n):
    for j in range(m):
        if matrix[i][j] == 0:
            row[i] = 1
            col[j] = 1

for i in range(n):
    for j in range(m):
        if row[i] or col[j] == 1:
            matrix[i][j] = 0 

In [18]:
col

[0, 1, 1]

In [19]:
row

[0, 1]

In [20]:
matrix

array([[2, 0, 0],
       [0, 0, 0]])

In [ ]:
ans = []
 
n = len(mat) # no. of rows
m = len(mat[0]) # no. of columns

# Initialize the pointers reqd for traversal.
top = 0
left = 0
bottom = n - 1
right = m - 1

    # Loop until all elements are not traversed.
while (top <= bottom and left <= right):
    # For moving left to right
    for i in range(left, right + 1):
        ans.append(mat[top][i])

    top += 1

    # For moving top to bottom.
    for i in range(top, bottom + 1):
        ans.append(mat[i][right])

    right -= 1

    # For moving right to left.
    if (top <= bottom):
        for i in range(right, left - 1, -1):
            ans.append(mat[bottom][i])

        bottom -= 1

    # For moving bottom to top.
    if (left <= right):
        for i in range(bottom, top - 1, -1):
            ans.append(mat[i][left])

        left += 1

   

In [44]:
from collections import defaultdict
arr = [1, 2, 3, -3, 1, 1, 1, 4, 2, -3]
n = len(arr)
k = 3
presum = 0
my_dict = defaultdict(int)
my_dict[0] = 1
count = 0  

In [45]:
for i in range(n):
    presum += arr[i]
    my_dict[presum] += 1
    remove = presum - k
    count = count + my_dict[remove]

In [46]:
my_dict

defaultdict(int,
            {0: 1,
             1: 1,
             -2: 0,
             3: 2,
             6: 2,
             4: 1,
             5: 1,
             2: 0,
             10: 1,
             7: 0,
             12: 1,
             9: 1})

In [47]:
count

8