STEP 3.2 MEDIUM

1. Two Sum

In [131]:
n = 9
target = 205
book = [575, 330, 339, 584, 239, 31, 173, 929, 967] 

In [132]:
book.sort()

In [133]:
book

[31, 173, 239, 330, 339, 575, 584, 929, 967]

In [134]:
book.sort()
left = 0
right = len(book) - 1
while left < right:
    if book[left] + book[right] > target:
        right -= 1
    elif book[left] + book[right] < target:
        left += 1
    else:
        print('YES')
        break

In [125]:
j

8

2. Sort An Array of 0s, 1s and 2s

In [146]:
n = 12
arr = [0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0]

In [198]:
arr = [2, 2, 2, 2, 0, 0, 1, 0]
n = 8

In [200]:
low = 0
mid = 0
high = n-1
while mid <= high:
    if arr[mid] == 0:
        arr[mid], arr[low] = arr[low], arr[mid]
        low += 1
        mid += 1
    
    elif arr[mid] == 1:
        mid += 1
    
    else:
        arr[mid], arr[high] = arr[high], arr[mid]
        high -= 1



X [0, 1, 0, 0, 2, 2, 2, 2]
X [0, 1, 0, 0, 2, 2, 2, 2]
X [0, 0, 1, 0, 2, 2, 2, 2]
X [0, 0, 0, 1, 2, 2, 2, 2]
X [0, 0, 0, 1, 2, 2, 2, 2]
X [0, 0, 0, 1, 2, 2, 2, 2]
X [0, 0, 0, 1, 2, 2, 2, 2]
X [0, 0, 0, 1, 2, 2, 2, 2]


In [201]:
arr

[0, 0, 0, 1, 2, 2, 2, 2]

In [202]:
arr.count(0)

3

3. Majority Element

In [ ]:
#MYSOLUTION(1st ATTEMPT)
def majorityElement(v: [int]) -> int:
    # Write your code here
    maxcount = 0
    num = 0
    n = len(v)
    vx = list(set(v))
    
    for i in range(len(vx)):
        if maxcount < v.count(vx[i]):
            maxcount = v.count(vx[i])
            num = vx[i]
    
    return num


In [203]:
arr = list(map(int, input().split()))

58 58 28 95 58 15 58 58 


In [204]:
arr

[58, 58, 28, 95, 58, 15, 58, 58]

In [205]:
for ele in arr:
    i = 0
    count = 0
    while i < n:
        if arr[i] == ele:
            count += 1
        else:
            count -= 1
        i += 1
    if count > 0:
        return ele

58
58
58
58
58


In [208]:
ele = 0
count = 0
for i in range(n):
    if count == 0:
        count = 1
        ele = arr[i]
        
    elif ele == arr[i]:
        count += 1
        
    else:
        count -= 1
        
if count(ele) > len(arr)/2:
    return ele
        
        

In [209]:
ele

58

4. Kadane’s Algorithm : Maximum Subarray Sum in an Array

In [214]:
arr = [10, 20, -30, 40, -50, 60]
n = len(arr)

In [217]:
maxsub = 0
for i in range(n):
    for j in range(n):
        sub = arr[i:j+1]
        if maxsub < sum(sub):
            maxsub = sum(sub)
            subans = sub
    
    

In [218]:
subans

[60]

In [219]:
#KADANE
sumarr = 0
maxi = arr[0]
for i in range(n):
    sumarr = sumarr + arr[i]
    if sumarr > maxi:
        maxi = sumarr
    if sumarr < 0:
        sumarr = 0

In [220]:
maxi

60

In [2]:
n = 37 
k = 52
arr = list(map(int, input().split()))

0 2 5 3 3 4 4 3 0 5 5 4 4 4 3 2 0 2 3 1 3 0 4 3 1 4 5 2 4 3 1 4 5 0 3 4 0


In [26]:
#KADANE

maxcount = 0


for i in range(n):
    count = 0
    sumarr = 0
    for j in range(i,n):
        if sumarr == k:
            break
        else:
            sumarr = sumarr + arr[j]
            count += 1
        
        if count > maxcount:
            maxcount = count
            
print(maxcount)

    

37


5. Longest Subarray With Sum K (DOUBT)

In [59]:
arr = [1,2,-33,4,-5,6]
n = len(arr)

In [63]:
sumarr = 0
maxi = arr[0]
for i in range(n):
    sumarr  += arr[i]
    if sumarr < 0: 
        sumarr = 0
    
    if sumarr > maxi: 
        maxi = sumarr
        print(maxi)
    

3
-33
4
-5
6


In [62]:
maxi

6

In [57]:
a = [1, 2, 1, 3]
n = len(a)
k = 2

In [58]:
suma = 0
count = 0
maxi = 0
for i in range(n):
    suma += a[i]
    count += 1
    if suma == k:
        
    print(count,suma)

1 1
2 3
3 4
4 7


In [46]:
maxlen

0

In [43]:
n

4

In [64]:
suma = 0
count = 0
maxlen = 0
for i in range(len(a)):
    suma = suma + a[i]
    count = count + 1
    if suma == k: 
        maxlen = count
        suma = 0
        count = 0
    if suma > k:
        suma = 


6. Best time to buy and sell stock

In [64]:
prices = [7, 1, 5, 4, 3, 6]
n = len(prices)

In [65]:
maxpr = 0
for i in range(n-1):
    print(prices[i],'/n')
    for j in range(i+1,n):
        profit = prices[j] - prices[i]
        maxpr = max(maxpr,profit)
print(maxpr)

7 /n
1 /n
5 /n
4 /n
3 /n
5


In [66]:
maxpr = 0
mini = prices[0]

for i in range(n):
    pr = prices[i] - mini
    maxpr = max(pr, maxpr)
    mini = min(mini, prices[i])

In [67]:
maxpr

5

7. Alternate Numbers

In [13]:
A = [1, 2, -3, -1, -2, 3]
n = len(A)

In [14]:
# BRUTE FORCE
pos = []
neg = []
for i in range(n):
    if A[i] >= 0:
        pos.append(A[i])
    else:
        neg.append(A[i])
        
for i in range(int(n/2)):
    A[2 * i] = pos[i] 
    A[2 * i + 1] = neg[i]


In [15]:
pos

[1, 2, 3]

In [16]:
neg

[-3, -1, -2]

In [19]:
A

[1, -3, 2, -1, 3, -2]

In [28]:
posIndex = 0
negIndex = 1
for i in range(n):
    if A[i] > 0:
        arr[posIndex] = A[i]
        posIndex += 2
        
    else:
        arr[negIndex] = A[i]
        negIndex += 2

In [29]:
arr

[1, -3, 2, -1, 3, -2]

8. NEXT PERMUTATION

In [180]:
arr = [5,4,3,2,1]
n = len(arr)

In [181]:
ind = -1
# (starting value, end, step)
for i in range(n - 2, -1, -1):
    if arr[i] < arr[i+1]:
        ind = i
        break
if ind == -1:
    arr = arr[::-1]
    print(arr)
else:
    for i in range(n-1, ind, -1):
        if arr[i] > arr[ind]: 
            arr[i], arr[ind] = arr[ind], arr[i]
            break

    arr[ind+1: n] = reversed(arr[ind+1: n])
    print(arr)

[1, 2, 3, 4, 5]


In [177]:
arr

[5, 4, 3, 2, 1]

In [168]:
arr[ind+1:n] = reversed(arr[ind+1: n])

In [146]:
ind

1

In [147]:
arr[-1]

0

In [111]:
arr

[2, 1, 5, 4, 3, 0, 0]

In [141]:
arr = reversed(arr[ind + 1:n-1])

In [142]:
arr

In [154]:
list(reversed(arr[ind+1:n]))

[0, 0, 1, 4, 5]

In [153]:
arr

[2, 3, 5, 4, 1, 0, 0]

9. SUPERIOR ELEMENTS

In [182]:
a = [1, 2, 2, 1]
n = len(a)

In [205]:
# BRUTE FORCE
b = []
for i in range(n):
    flag = 0
    for j in range(i+1,n):
        print(a[i],a[j])
        if a[i] <= a[j]:
            flag = 1
            break
    if flag == 0:
        b.append(a[i])
return b

1 2
1 2
1 1
2 2
2 1
2 1


In [206]:
b

[2, 1]

In [219]:
# OPTIMAL
b = []
for i in range(n-1):
    if a[i] > max(a[i+1:]):
        b.append(a[i])
b.append(a[n-1])
b.sort()

In [214]:
for i in range(n-1):
    print(a[i],a[i+1:])

1 [2, 2, 1]
2 [2, 1]
2 [1]


In [216]:
a[n-1]

1

In [220]:
b

[1, 2]

In [232]:
b = []
maxi = float('-inf')
for i in range(n-1, -1, -1):
    if a[i] > maxi:
        b.append(a[i])
    maxi = max(maxi,a[i])
b.sort()

In [227]:
a = [1, 2, 4, 1]
n = len(a)

In [224]:
a

[1, 2, 2, 1]

In [230]:
maxi = float('-inf')

In [231]:
maxi

-inf

10. Longest successive elements

In [255]:
a = [1, 2, 2, 1]

In [256]:
a = list(set(a))
n = len(a)
count = 1
maxc = 0
for i in range(n-1):
    print(a[i],a[i+1])
    if a[i+1] - a[i] == 1:
        count += 1
    else:
        count = 0
    maxc = max(maxc, count)

1 2


In [254]:
maxc

5

In [263]:
# OPTIMAL
a = [5, 8, 3, 2, 1, 4, 9, 10]
n = len(a)

longest = 1
st = set()
for i in range(n):
    st.add(a[i])
    
for ele in st:
    if ele - 1 not in st:
        x = ele
        cnt = 1
        while x + 1 in st:
            x += 1
            cnt += 1
        longest = max(longest, cnt)
      

In [260]:
st

{1, 2, 3, 4, 5, 8}

In [264]:
longest

5

11. Zero Matrix

In [3]:
import numpy as np
matrix = np.array([
    [2, 4, 3],
    [1, 0, 0]
])

In [4]:
n = len(matrix)
m = len(matrix[0])

In [5]:
matrix

array([[2, 4, 3],
       [1, 0, 0]])

In [372]:
#BRUTE
def markRow(matrix, n, m, i):
    # set all non-zero elements as -1 in the row i:
    for j in range(m):
        if matrix[i][j] != 0:
            matrix[i][j] = -1

def markCol(matrix, n, m, j):
    # set all non-zero elements as -1 in the col j:
    for i in range(n):
        if matrix[i][j] != 0:
            matrix[i][j] = -1

def zeroMatrix(matrix, n, m):
    # Set -1 for rows and cols
    # that contains 0. Don't mark any 0 as -1:
    for i in range(n):
        for j in range(m):
            if matrix[i][j] == 0:
                markRow(matrix, n, m, i)
                markCol(matrix, n, m, j)
    
    # Finally, mark all -1 as 0:
    for i in range(n):
        for j in range(m):
            if matrix[i][j] == -1:
                matrix[i][j] = 0
    
    return matrix

In [373]:
zeroMatrix(matrix, n, m)

array([[2, 0, 0],
       [0, 0, 0]])

In [16]:
import numpy as np
matrix = np.array([
    [2, 4, 3],
    [1, 0, 0]
])

In [17]:
# BETTER
row = [0] * n
col = [0] * m

In [18]:
n = len(matrix)
m = len(matrix[0])

In [19]:
matrix

array([[2, 4, 3],
       [1, 0, 0]])

In [20]:
row

[0, 0]

In [24]:
for i in range(n):
    for j in range(m):
        if matrix[i][j] == 0:
            row[i] = 1
            col[j] = 1
            
for i in range(n):
    for j in range(m):
        if row[i] == 1 or col[j] == 1:
            matrix[i][j] = 0

In [22]:
row

[0, 1]

In [23]:
col

[0, 1, 1]

In [25]:
matrix

array([[2, 0, 0],
       [0, 0, 0]])

In [56]:
# OPTIMAL
import numpy as np
matrix = np.array([
    [1, 1, 1, 1],
    [1, 0, 1, 1],
    [1, 1, 0, 1],
    [0, 1, 1, 0]
])

In [57]:
n = len(matrix)
m = len(matrix[0])

In [58]:
# ROW STRIP
matrix[:,0]

array([1, 1, 1, 0])

In [59]:
# COLUMN STRIP
matrix[0]

array([1, 1, 1, 1])

In [64]:
col0 = 1
for i in range(n):
    for j in range(m):
        if matrix[i][j] == 0:
            matrix[i][0] = 0 #Row Strip
            if j!= 0:
                matrix[0][j] = 0 #Col strip
            else:
                col0 = 0
                
# Marking inner matrix 0
for i in range(1,n):
    for j in range(1,m):
        # JO JO 0 NAHI HAI
        if matrix[i][j] != 0:
            if matrix[i][0] == 0 or matrix[0][j] == 0:
                matrix[i][j] == 0

if matrix[0][0] == 0:
    # mark column strip 0
    for j in range(m):
        matrix[0][j] = 0
if col0 == 0:
    for i in range(n):
        matrix[i][0] = 0
                
                

In [ ]:
from sys import *
from collections import *
from math import *


def zeroMatrix(matrix, n, m):

    col0 = 1
    for i in range(n):
        for j in range(m):
            if matrix[i][j] == 0:
                matrix[i][0] = 0

                if j != 0:
                    matrix[0][j] = 0
                else:
                    col0 = 0

    for i in range(1, n):
        for j in range(1, m):
            if matrix[i][j] != 0:
                # check for col & row:
                if matrix[i][0] == 0 or matrix[0][j] == 0:
                    matrix[i][j] = 0

    if matrix[0][0] == 0:
        for j in range(m):
            matrix[0][j] = 0
    if col0 == 0:
        for i in range(n):
            matrix[i][0] = 0

    return matrix



In [63]:
matrix

array([[0, 0, 0, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 1],
       [0, 1, 1, 0]])

12. Rotate Matrix by 90 degrees

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [19]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
#BRUTE
n = len(matrix)
ans = np.zeros((n, n), dtype = int)
for i in range(n):
    for j in range(n):
        ans[j][(n-1) - i] = matrix[i][j]

In [22]:
ans

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
matrix

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [85]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [87]:
n = len(matrix)

In [88]:
#OPTIMAL
n = len(matrix)
for i in range(n):
    for j in range(i):
        matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
for i in range(n):
    matrix[i] = matrix[i][::-1]

In [89]:
matrix

array([[13,  9,  5,  1],
       [14, 10,  6,  2],
       [15, 11,  7,  3],
       [16, 12,  8,  4]])

13. Print the matrix in spiral manner

In [48]:
matrix = np.array([[1, 2, 3, 4, 5, 6], [20, 21, 22, 23, 24, 7], [19, 32, 33, 34, 25, 8], [18, 31, 36, 35, 26, 9], [17, 30, 29, 28, 27, 10], [16, 15, 14, 13, 12, 11]])

In [49]:
matrix

array([[ 1,  2,  3,  4,  5,  6],
       [20, 21, 22, 23, 24,  7],
       [19, 32, 33, 34, 25,  8],
       [18, 31, 36, 35, 26,  9],
       [17, 30, 29, 28, 27, 10],
       [16, 15, 14, 13, 12, 11]])

In [71]:
matrix = np.array([[1, 3, 7, 9], [10, 12, 15, 17], [19, 20, 21, 50] ])

In [74]:
n = len(matrix)
m = len(matrix[0])
left = 0
right = m - 1
top = 0
bottom = n - 1
ans = []
while (top <= bottom and left <= right):
    
    # GOING RIGHT
    for i in range(left, right + 1):
        ans.append(matrix[top][i])
    top += 1
   

    # GOING DOWN
    for i in range(top, bottom + 1):
        ans.append(matrix[i][right])
    right -= 1
 
    
    # GOING LEFT
    if top <= bottom:
        for i in range(right, left - 1, -1):
            ans.append(matrix[bottom][i])
        bottom -= 1
   
   
    # GOING UP
    if left <= right:
        for i in range(bottom, top - 1, -1):
            ans.append(matrix[i][left])
        left += 1
   
    

In [75]:
ans

[1, 3, 7, 9, 17, 50, 21, 20, 19, 10, 12, 15]

14. Count subarrays with given sum

In [1]:
arr = [3, 1, 2, 4]
n = len(arr)
k = 6

In [10]:
count = 0
for i in range(n):
    sumarr = 0
    for j in range(i, n):
        sumarr += arr[j]
        if sumarr == k:
            count += 1
            break
        elif sumarr > k:
            break

In [11]:
count

2

In [15]:
from collections import defaultdict
#OPTIMAL
arr = [1, 2, 3, -3, 1, 1, 1, 4, 2, -3]
n = len(arr)
k = 3

In [19]:
mpp = defaultdict(int)  
preSum = 0             
cnt = 0                
mpp[0] = 1               
for i in range(n):
    preSum += arr[i]
    remove = preSum - k 
    mpp[preSum] += 1
    cnt += mpp[remove]
  
    

In [20]:
mpp

defaultdict(int,
            {0: 1,
             1: 1,
             -2: 0,
             3: 2,
             6: 2,
             4: 1,
             5: 1,
             2: 0,
             10: 1,
             7: 0,
             12: 1,
             9: 1})

In [21]:
cnt

8